"""empty message

Revision ID: 28260a4946e4
Revises: 29b052ee87b4
Create Date: 2015-01-28 13:32:07.652539

"""

# revision identifiers, used by Alembic.
revision = '28260a4946e4'
down_revision = '29b052ee87b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('pohlavi', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_prijmeni', 'loguser', ['prijmeni'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loguser_prijmeni', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
