"""empty message

Revision ID: 3d51260d9f81
Revises: 28260a4946e4
Create Date: 2015-02-18 12:38:38.886066

"""

# revision identifiers, used by Alembic.
revision = '3d51260d9f81'
down_revision = '28260a4946e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Tomas', sa.String(), nullable=False),
    sa.Column('Michalovsky', sa.String(), nullable=False),
    sa.Column('sloupec3', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser2'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser2_sloupec3', 'loguser2', ['sloupec3'], unique=False)
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_index('ix_loguser2_sloupec3', table_name='loguser2')
    op.drop_table('loguser2')
    ### end Alembic commands ###
